name: .NET Core

on:
  - push
  - pull_request

jobs:
  build:

    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Run sonarscanner
      uses: Secbyte/dotnet-sonarscanner@v2.3
      with:
        buildCommand: dotnet build .
        testCommand: dotnet test . --collect:"XPlat Code Coverage" --logger trx
        projectKey: minecraftplayer456_MCSM
        projectName: MCSM
        sonarOrganisation: minecraftplayer456
        beginArguments: >
          /d:sonar.verbose="true"
          /d:sonar.cs.opencover.reportsPaths='"**/coverage.cobertura.xml"'
          /d:sonar.cs.vstest.reportsPath='"**/*.trx"'
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}